### ISSUE TITLE
purge does nothing?

### ISSUE THREAD

**Issue by Deracination** [net-amqp-rabbitmq/net-amqp-rabbitmq#149]
Using Net-AMQP-RabbitMQ-2.30000, Perl 5.24.0

calling 'purge' doesn't seem to do anything. The test below fails because the message remains in the queue.

```
use strict;
use Test::More tests => 3;
use Data::Dumper;
use Net::AMQP::RabbitMQ;

my $qn = "TEST_$$";
my $q=Net::AMQP::RabbitMQ->new();

$q->connect( 'localhost', { user => 'guest', password => 'guest' });
$q->channel_open(1);
$q->queue_declare(1,$qn, { auto_delete => 1 });
$q->consume(1,$qn, { no_ack => 1 });

$q->publish(1,$qn,"hello $$",{},{});

my $msg=$q->recv(10);

ok($msg && $msg->{body} eq "hello $$",'payload');

$msg=$q->recv(10);

ok(!$msg,'no message');

$q->publish(1,$qn,"hello2 $$!",{},{});

$q->purge(1,$qn);

$msg=$q->recv(10);

ok(!$msg,'no message (purged)') or diag Dumper $msg;

$q->queue_delete(1,$qn, { if_unused=>0, if_empty=>0 });
```

**Comment by manchicken** [comment]
@Deracination Are you able to replicate this on 2.40011? I'm going to investigate for 2.40013, but I'm hoping it's already been resolved in some of the more recent updates.

**Comment by manchicken** [comment]
Hey @Deracination, I just added this test to #250, and it passes. I can't figure out how to replicate this.

My suspicion is that you're using `consume()` and `recv()` in a manner which is buffering the messages between the `publish()` and the `purge()` calls, so that when you issued the `purge()` call the message has already been delivered to the consumer.

Please review the test in the PR and let me know if you think I missed something. I'll move this issue to the 2.40012 milestone.
