### ISSUE TITLE
queue_delete drops connection instead closing channel

### ISSUE THREAD

**Issue by migotom** [net-amqp-rabbitmq/net-amqp-rabbitmq#159]
Method queue_delete drops whole connection if fails to delete queue (eg. consumer connected) instead closing channel as described in [module spec](https://metacpan.org/pod/Net::AMQP::RabbitMQ#queue_delete($channel,-$queuename,-$options)) (RabbitMQ throws [channel exception](https://www.rabbitmq.com/amqp-0-9-1-reference.html) ).

Lib throws error while trying to reopen channel:

`AMQP socket not connected at amqp_queue_delete_issue.pl line 29`

Attached code used to recreate issue: [amqp_queue_delete_issue.pl.txt](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/files/2464708/amqp_queue_delete_issue.pl.txt)

**Comment by manchicken** [comment]
Many times the issue isn't so much that the socket was disconnected as it was that you tried to make an RPC call when the connection was in an error state. I've been trying to think through this problem for a while (more than a year, off and on), but there really aren't any good ways I've found so far to handle this limitation of the C library. This same issue is also what is getting in the way of upgrading the C library in general. I've been working on a refactor to use more of the C code instead of the copy-and-paste code which exists in the module now, but it's just taking a while.
