### ISSUE TITLE
Publishing to a non-existent exchange and then using the same instance can cause `get()` errors.

### ISSUE THREAD

**Issue by manchicken** [net-amqp-rabbitmq/net-amqp-rabbitmq#24]
If you `publish()` to an exchange that doesn't exist and then you call a `get()` on a different channel, you get an "Unexpected header 1!" error.

**Comment by zbentley** [comment]
This is likely because there's a difference between `NO_ROUTE` errors (publishing to an exchange in `MANDATORY` mode without a bound queue at the end of the exchange routing path) and `NOT_FOUND` errors (publishing to an object, queue or exchange, that does not exist). `NO_ROUTE` is a "soft" error (it doesn't close the channel, so error frames might still be lingering in there for the subsequent call to `get()`); `NOT_FOUND` is a hard, channel-closing error.

**Comment by manchicken** [comment]
We talked about this in other issues, but this is because error messages are sent asynchronously, so it may not get back to your program straight away. 

This is an upstream limitation I believe.

**Comment by markwellis** [comment]
I think we can close this issues, as there's nothing we can do to fix it.

**Comment by markwellis** [comment]
I'm closing this issue. Feel free to reopen it if you discover more info or a way to fix it
