### ISSUE TITLE
host our own rabbitmq for tests

### ISSUE THREAD

**Issue by eserte** [net-amqp-rabbitmq/net-amqp-rabbitmq#53]
http://dev.rabbitmq.com/mgmt/#/queues is down for more than two weeks, causing the Net-AMQP-RabbitMQ test suite to fail, see http://matrix.cpantesters.org/?dist=Net-AMQP-RabbitMQ%200.310000;reports=1#sl=7,1

I don't know if this is a temporary problem, if somebody at rabbitmq.com should be contacted, or maybe the test suite should not do any remote tests by default.

**Comment by manchicken** [comment]
That's a great point!

**Comment by markwellis** [comment]
it is a good point, but the problem is the cpan testers won't be able to smoke test this for us. which is fine, the bigger concern i have is if you install this, then the tests will only work if you have a local rabbitmq setup and running.

I guess my question is, is it reasonable to expect a local rabbitmq server to be available if you're installing this module?

**Comment by manchicken** [comment]
No. I don't think it is. A rabbitmq server is an integration piece, so it
won't always be something that a user would get to install and use for our
test suite. We really need to have rabbitmq up somewhere for people to test
against.

**Comment by markwellis** [comment]
ok, i'll get this sorted by august, when i have a new server to put it on

**Comment by eserte** [comment]
dev.rabbitmq.com seems to work again.

**Comment by markwellis** [comment]
I'll be hosting a rabbitmq server soon, so it doesn't happen again in the future. Leaving open until then

**Comment by markwellis** [comment]
ok, i've done this. the server is there. so moving the rest to #27
